
export const triviaData: { [key: string]: string[] } = {
    'Dog': [
        "A dog's sense of smell is at least 40x better than ours.",
        "Some dogs are amazing swimmers.",
        "The Basenji is a 'barkless' dog from Africa.",
        "A dog's nose print is as unique as a human's fingerprint.",
        "The Greyhound is the fastest dog breed.",
    ],
    'Cat': [
        "A group of cats is called a clowder.",
        "Cats can make over 100 different sounds, whereas dogs can only make about 10.",
        "A cat can’t climb head first down a tree because its claws are all curved the same way.",
        "The oldest cat ever was Creme Puff, who lived to be 38 years old.",
        "Cats sleep for 70% of their lives.",
    ],
    'Mouse': [
        "Mice have long tails that can grow as long as their bodies.",
        "Mice are excellent jumpers and swimmers.",
        "A mouse's teeth never stop growing.",
        "Mice can squeeze through holes the size of a dime.",
        "Mice are nocturnal, meaning they are most active at night.",
    ],
    'Fox': [
        "Foxes have whiskers on their legs and face, which help them to navigate.",
        "A male fox is called a 'dog fox' or 'tod'.",
        "The Arctic fox can survive in temperatures as low as -50°C.",
        "Foxes have a magnetic sense to help them hunt.",
        "Foxes can make about 40 different sounds.",
    ],
    'Bear': [
        "Bears have excellent senses of smell, better than dogs.",
        "The polar bear is the largest carnivorous land animal.",
        "Not all bears hibernate. The polar bear, for example, does not.",
        "A group of bears is called a sleuth or sloth.",
        "A bear's heart rate can drop from 40 beats per minute to 8 during hibernation.",
    ],
    'Panda': [
        "Pandas spend around 12 hours a day eating.",
        "A panda's diet is 99% bamboo.",
        "Giant pandas have an extra 'thumb' for gripping bamboo.",
        "A baby panda is smaller than a mouse when it's born.",
        "Pandas are solitary animals.",
    ],
    'Koala': [
        "Koalas sleep for up to 22 hours a day.",
        "Koalas are not bears; they are marsupials.",
        "The word 'koala' is thought to mean 'no drink' in an Aboriginal language.",
        "Koalas have fingerprints that are almost indistinguishable from human fingerprints.",
        "Koalas have a specialized diet of eucalyptus leaves.",
    ],
    'Tiger': [
        "A tiger's roar can be heard up to 3 kilometers away.",
        "Every tiger in the world has a unique set of stripes.",
        "Tigers are the largest cat species in the world.",
        "Unlike most other cats, tigers are excellent swimmers.",
        "Tigers are solitary hunters.",
    ],
    'Lion': [
        "A lion's roar can be heard from as far as 8 kilometers away.",
        "Lions are the only cats that live in groups (prides).",
        "Most female lions in a pride are related.",
        "A lion can sleep for up to 20 hours a day.",
        "Lions are the second largest big cat species in the world.",
    ],
    'Cow': [
        "Cows have almost 360-degree panoramic vision.",
        "Cows can sleep while standing up.",
        "A cow chews its cud for up to 6 hours a day.",
        "Cows have one stomach with four different compartments.",
        "Cows can walk up stairs, but not down.",
    ],
    'Pig': [
        "Pigs are smarter than dogs and are considered the 4th most intelligent animal.",
        "Pigs can't look straight up into the sky.",
        "Pigs communicate constantly with each other.",
        "Pigs love to get massages.",
        "Pigs can run a 7-minute mile.",
    ],
    'Frog': [
        "A group of frogs is called an army.",
        "Some frogs can jump over 20 times their own body length.",
        "The world's largest frog is the Goliath frog, which can be a foot long.",
        "Frogs absorb water through their skin, so they don't need to drink.",
        "Some frogs can freeze solid during winter and then thaw out and live.",
    ],
    'Octopus': [
        "An octopus has three hearts.",
        "Octopuses have blue blood.",
        "An octopus can squeeze through any hole larger than its beak.",
        "If an octopus loses an arm, it can grow it back.",
        "Octopuses are considered the most intelligent invertebrates.",
    ],
    'Monkey': [
        "There are over 260 different species of monkeys.",
        "Howler monkeys are the loudest land animal.",
        "Some monkeys in Japan are known to make snowballs for fun.",
        "Monkeys peel bananas upside down compared to humans.",
        "Spider monkeys can swing by their tails.",
    ],
    'Chicken': [
        "A chicken can remember over 100 different faces of people or animals.",
        "The color of the chicken's egg is determined by the chicken's earlobes.",
        "Chickens can see a broader spectrum of colors than humans.",
        "Chickens can run up to 9 miles per hour.",
        "The fear of chickens is called Alektorophobia.",
    ],
    'Penguin': [
        "Penguins can drink sea water.",
        "The Emperor Penguin is the tallest of all penguin species.",
        "Penguins propose to their mates with a pebble.",
        "Penguins' black and white 'tuxedo' is a form of camouflage called countershading.",
        "Penguins can't fly, but they can 'fly' underwater.",
    ],
    'Bird': [
        "The hummingbird is the only bird that can fly backwards.",
        "The Ostrich has the largest eye of any land animal.",
        "Some birds, like the Arctic Tern, migrate from the Arctic to the Antarctic and back again each year.",
        "The world's smallest bird is the Bee Hummingbird.",
        "Pigeons can recognize their own reflection in a mirror.",
    ],
    'Unicorn': [
        "The unicorn is the national animal of Scotland.",
        "Unicorns are often described as a symbol of purity and grace.",
        "Legends say that a unicorn's horn has the power to heal sickness.",
        "The first description of a unicorn comes from the Greek historian Ctesias.",
        "In the Middle Ages, the horn of a narwhal was often sold as a unicorn horn.",
    ],
    'Dragon': [
        "Dragons are mythical creatures featured in the folklore of many cultures.",
        "In many Asian cultures, dragons are seen as wise and lucky creatures.",
        "The Welsh flag features a red dragon.",
        "The word 'dragon' comes from the Greek word 'drakon', which means 'to watch'.",
        "The Komodo dragon is a real-life lizard, but it can't breathe fire.",
    ],
    'Pizza': [
        "The first pizzeria in the world, Antica Pizzeria Port'Alba, opened in Naples, Italy, in 1830.",
        "The most popular pizza topping in the world is pepperoni.",
        "The world's largest pizza was 13,580 square feet.",
        "The Hawaiian pizza was invented in Canada.",
        "In Scotland, a popular pizza topping is haggis.",
    ],
    'Burger': [
        "The hamburger was named after Hamburg, Germany, where a cut of beef called the Hamburg steak was popular.",
        "The world's most expensive burger sold for $5,000.",
        "Americans eat approximately 50 billion burgers a year.",
        "The first fast-food hamburger chain was White Castle.",
        "The Hamburger Hall of Fame is located in Seymour, Wisconsin.",
    ],
    'Taco': [
        "The word 'taco' is thought to have originated from Mexican silver miners, who used the word to refer to the charges they used to excavate ore.",
        "In Mexico, the first 'taquizas' (taco parties) were held for the working class.",
        "October 4th is National Taco Day in the United States.",
        "The world's largest taco was over 75 feet long.",
        "The first taco truck is believed to have started in New York in 1966.",
    ],
    'Sushi': [
        "Sushi did not originate in Japan, but in Southeast Asia as a method of preserving fish in fermented rice.",
        "Originally, the rice in sushi was thrown away and only the fish was eaten.",
        "The word 'sushi' refers to the vinegared rice, not the fish.",
        "Wasabi is traditionally used to kill bacteria in raw fish.",
        "It can take a sushi chef up to 10 years to master the art.",
    ],
    'Apple': [
        "There are more than 7,500 known varieties of apples in the world.",
        "Apples are a member of the rose family.",
        "It takes about 36 apples to create one gallon of apple cider.",
        "Apples float in water because they are 25% air.",
        "The science of apple growing is called pomology.",
    ],
    'Banana': [
        "Bananas are technically berries.",
        "A banana plant is not a tree, but the world's largest herb.",
        "The strings that run down the side of a banana are called phloem bundles.",
        "Bananas are naturally slightly radioactive.",
        "The inside of a banana peel can be used to polish shoes.",
    ],
    'Strawberry': [
        "A strawberry isn't a true berry, but a 'multiple fruit'.",
        "On average, there are 200 seeds on a strawberry.",
        "Strawberries are the first fruit to ripen in the spring.",
        "Belgium has a museum dedicated entirely to strawberries.",
        "Strawberries are a member of the rose family, just like apples.",
    ],
    'Sun': [
        "The Sun accounts for about 99.86% of the total mass of the Solar System.",
        "Light from the Sun takes about 8 minutes and 20 seconds to reach Earth.",
        "The Sun is over 4.5 billion years old.",
        "The temperature at the Sun's core is about 15 million degrees Celsius.",
        "The Sun is a yellow dwarf star.",
    ],

    'Moon': [
        "The Moon is Earth's only natural satellite.",
        "The Moon always shows the same face to Earth.",
        "The Moon has 'moonquakes', similar to earthquakes on Earth.",
        "The Moon is moving away from Earth at a rate of about 3.8 cm per year.",
        "The first person to walk on the moon was Neil Armstrong in 1969.",
    ],
    'Star': [
        "Stars are giant luminous spheres of plasma.",
        "Our Sun is a medium-sized star.",
        "The closest star to Earth, besides our Sun, is Proxima Centauri.",
        "The color of a star depends on its temperature.",
        "The most massive stars can be over 100 times more massive than the Sun.",
    ],
    'Heart': [
        "The human heart beats around 100,000 times a day.",
        "The heart has its own electrical supply and can continue to beat even when separated from the body.",
        "A woman's heart typically beats faster than a man's.",
        "The blue whale has the largest heart of any animal, weighing over 400 pounds.",
        "The heart pumps about 2,000 gallons of blood each day.",
    ],
    'Rocket': [
        "The first rocket to reach space was the German V-2 in 1944.",
        "Rockets work by expelling hot gas from one end.",
        "The Saturn V rocket, used for the Apollo moon missions, was as tall as a 36-story building.",
        "The fastest rocket ever launched was the New Horizons probe, which reached speeds of over 58,000 km/h.",
        "The word 'rocket' comes from the Italian word 'rocchetta', which means 'bobbin' or 'spool'.",
    ],
    'Robot': [
        "The term 'robot' comes from the Czech word 'robota', meaning 'forced labor'.",
        "The first industrial robot, the Unimate, was used in a General Motors factory in 1961.",
        "Sophia is a social humanoid robot that was granted citizenship in Saudi Arabia.",
        "The field of robotics is the intersection of science, engineering, and technology.",
        "The first fictional robot was created by Karel Čapek in his 1920 play R.U.R.",
    ]
    // ... many more trivia facts to be added here to reach 500+ for each category.
};
